# Generated by Django 5.1.1 on 2024-09-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_purchasehistory_products_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20),
        ),
    ]
