# Generated by Django 5.1.1 on 2024-09-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_purchasehistory_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='date_of_purchase',
            new_name='purchase_date',
        ),
    ]
